//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Usage4Claude.Resources;

using System;
using System.Resources;
using System.Globalization;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Strings
{
    private static global::System.Resources.ResourceManager? resourceMan;
    private static global::System.Globalization.CultureInfo? resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Strings()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Usage4Claude.Resources.Strings", typeof(Strings).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo? Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Usage4Claude.
    /// </summary>
    public static string AppName
    {
        get { return ResourceManager.GetString("AppName", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to No account.
    /// </summary>
    public static string NoAccount
    {
        get { return ResourceManager.GetString("NoAccount", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to No data.
    /// </summary>
    public static string NoData
    {
        get { return ResourceManager.GetString("NoData", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Refreshing....
    /// </summary>
    public static string Refreshing
    {
        get { return ResourceManager.GetString("Refreshing", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Resetting....
    /// </summary>
    public static string Resetting
    {
        get { return ResourceManager.GetString("Resetting", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Updated {0}.
    /// </summary>
    public static string Updated
    {
        get { return ResourceManager.GetString("Updated", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Error: {0}.
    /// </summary>
    public static string Error
    {
        get { return ResourceManager.GetString("Error", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Usage4Claude - No data.
    /// </summary>
    public static string TrayNoData
    {
        get { return ResourceManager.GetString("TrayNoData", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Usage4Claude - Refreshing....
    /// </summary>
    public static string TrayRefreshing
    {
        get { return ResourceManager.GetString("TrayRefreshing", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Usage4Claude - {0:F0}%.
    /// </summary>
    public static string TrayUsage
    {
        get { return ResourceManager.GetString("TrayUsage", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Usage4Claude - {0:F0}% ({1}).
    /// </summary>
    public static string TrayUsageWithTime
    {
        get { return ResourceManager.GetString("TrayUsageWithTime", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Refresh.
    /// </summary>
    public static string MenuRefresh
    {
        get { return ResourceManager.GetString("MenuRefresh", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Settings.
    /// </summary>
    public static string MenuSettings
    {
        get { return ResourceManager.GetString("MenuSettings", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Exit.
    /// </summary>
    public static string MenuExit
    {
        get { return ResourceManager.GetString("MenuExit", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Settings.
    /// </summary>
    public static string SettingsTitle
    {
        get { return ResourceManager.GetString("SettingsTitle", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to General.
    /// </summary>
    public static string SettingsGeneral
    {
        get { return ResourceManager.GetString("SettingsGeneral", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Auth.
    /// </summary>
    public static string SettingsAuth
    {
        get { return ResourceManager.GetString("SettingsAuth", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to About.
    /// </summary>
    public static string SettingsAbout
    {
        get { return ResourceManager.GetString("SettingsAbout", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Display.
    /// </summary>
    public static string DisplaySection
    {
        get { return ResourceManager.GetString("DisplaySection", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Choose what to show in the system tray icon..
    /// </summary>
    public static string DisplayDescription
    {
        get { return ResourceManager.GetString("DisplayDescription", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Show icon.
    /// </summary>
    public static string ShowIcon
    {
        get { return ResourceManager.GetString("ShowIcon", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Show percentage.
    /// </summary>
    public static string ShowPercentage
    {
        get { return ResourceManager.GetString("ShowPercentage", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Display Options.
    /// </summary>
    public static string DisplayOptionsSection
    {
        get { return ResourceManager.GetString("DisplayOptionsSection", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Choose which usage limits to display..
    /// </summary>
    public static string DisplayOptionsDescription
    {
        get { return ResourceManager.GetString("DisplayOptionsDescription", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Smart (auto).
    /// </summary>
    public static string SmartMode
    {
        get { return ResourceManager.GetString("SmartMode", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Custom.
    /// </summary>
    public static string CustomMode
    {
        get { return ResourceManager.GetString("CustomMode", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to 5-hour limit.
    /// </summary>
    public static string FiveHourLimit
    {
        get { return ResourceManager.GetString("FiveHourLimit", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to 7-day limit.
    /// </summary>
    public static string SevenDayLimit
    {
        get { return ResourceManager.GetString("SevenDayLimit", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Extra usage.
    /// </summary>
    public static string ExtraUsage
    {
        get { return ResourceManager.GetString("ExtraUsage", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Opus weekly.
    /// </summary>
    public static string OpusWeekly
    {
        get { return ResourceManager.GetString("OpusWeekly", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Sonnet weekly.
    /// </summary>
    public static string SonnetWeekly
    {
        get { return ResourceManager.GetString("SonnetWeekly", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Refresh.
    /// </summary>
    public static string RefreshSection
    {
        get { return ResourceManager.GetString("RefreshSection", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Configure how usage data is refreshed..
    /// </summary>
    public static string RefreshDescription
    {
        get { return ResourceManager.GetString("RefreshDescription", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Smart refresh.
    /// </summary>
    public static string SmartRefresh
    {
        get { return ResourceManager.GetString("SmartRefresh", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Fixed interval.
    /// </summary>
    public static string FixedInterval
    {
        get { return ResourceManager.GetString("FixedInterval", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Refresh interval:.
    /// </summary>
    public static string RefreshInterval
    {
        get { return ResourceManager.GetString("RefreshInterval", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Notifications.
    /// </summary>
    public static string NotificationsSection
    {
        get { return ResourceManager.GetString("NotificationsSection", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Get notified about usage changes..
    /// </summary>
    public static string NotificationsDescription
    {
        get { return ResourceManager.GetString("NotificationsDescription", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Enable notifications.
    /// </summary>
    public static string EnableNotifications
    {
        get { return ResourceManager.GetString("EnableNotifications", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Appearance.
    /// </summary>
    public static string AppearanceSection
    {
        get { return ResourceManager.GetString("AppearanceSection", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Choose the application theme..
    /// </summary>
    public static string AppearanceDescription
    {
        get { return ResourceManager.GetString("AppearanceDescription", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to System.
    /// </summary>
    public static string AppearanceSystem
    {
        get { return ResourceManager.GetString("AppearanceSystem", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Light.
    /// </summary>
    public static string AppearanceLight
    {
        get { return ResourceManager.GetString("AppearanceLight", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Dark.
    /// </summary>
    public static string AppearanceDark
    {
        get { return ResourceManager.GetString("AppearanceDark", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Time Format.
    /// </summary>
    public static string TimeFormatSection
    {
        get { return ResourceManager.GetString("TimeFormatSection", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Choose how reset times are displayed..
    /// </summary>
    public static string TimeFormatDescription
    {
        get { return ResourceManager.GetString("TimeFormatDescription", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to System default.
    /// </summary>
    public static string TimeFormatSystem
    {
        get { return ResourceManager.GetString("TimeFormatSystem", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to 12-hour (AM/PM).
    /// </summary>
    public static string TimeFormat12
    {
        get { return ResourceManager.GetString("TimeFormat12", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to 24-hour.
    /// </summary>
    public static string TimeFormat24
    {
        get { return ResourceManager.GetString("TimeFormat24", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Language.
    /// </summary>
    public static string LanguageSection
    {
        get { return ResourceManager.GetString("LanguageSection", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Choose the application language..
    /// </summary>
    public static string LanguageDescription
    {
        get { return ResourceManager.GetString("LanguageDescription", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Startup.
    /// </summary>
    public static string StartupSection
    {
        get { return ResourceManager.GetString("StartupSection", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to System startup configuration..
    /// </summary>
    public static string StartupDescription
    {
        get { return ResourceManager.GetString("StartupDescription", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Launch at login.
    /// </summary>
    public static string LaunchAtLogin
    {
        get { return ResourceManager.GetString("LaunchAtLogin", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Accounts.
    /// </summary>
    public static string AccountsSection
    {
        get { return ResourceManager.GetString("AccountsSection", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Manage your Claude accounts..
    /// </summary>
    public static string AccountsDescription
    {
        get { return ResourceManager.GetString("AccountsDescription", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Set as Active.
    /// </summary>
    public static string SetAsActive
    {
        get { return ResourceManager.GetString("SetAsActive", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Remove Selected.
    /// </summary>
    public static string RemoveSelected
    {
        get { return ResourceManager.GetString("RemoveSelected", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Account Details.
    /// </summary>
    public static string AccountDetails
    {
        get { return ResourceManager.GetString("AccountDetails", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Display Name.
    /// </summary>
    public static string DisplayName
    {
        get { return ResourceManager.GetString("DisplayName", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Organization ID.
    /// </summary>
    public static string OrganizationId
    {
        get { return ResourceManager.GetString("OrganizationId", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Session Key.
    /// </summary>
    public static string SessionKey
    {
        get { return ResourceManager.GetString("SessionKey", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Save Changes.
    /// </summary>
    public static string SaveChanges
    {
        get { return ResourceManager.GetString("SaveChanges", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Add Account.
    /// </summary>
    public static string AddAccount
    {
        get { return ResourceManager.GetString("AddAccount", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Enter your session key and organization ID to add a new account..
    /// </summary>
    public static string AddAccountDescription
    {
        get { return ResourceManager.GetString("AddAccountDescription", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Display Name (optional).
    /// </summary>
    public static string DisplayNameOptional
    {
        get { return ResourceManager.GetString("DisplayNameOptional", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Browser Login.
    /// </summary>
    public static string BrowserLogin
    {
        get { return ResourceManager.GetString("BrowserLogin", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Connection Diagnostic.
    /// </summary>
    public static string ConnectionDiagnostic
    {
        get { return ResourceManager.GetString("ConnectionDiagnostic", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Test the connection to Claude API..
    /// </summary>
    public static string ConnectionDescription
    {
        get { return ResourceManager.GetString("ConnectionDescription", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Test Connection.
    /// </summary>
    public static string TestConnection
    {
        get { return ResourceManager.GetString("TestConnection", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Testing....
    /// </summary>
    public static string Testing
    {
        get { return ResourceManager.GetString("Testing", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Active.
    /// </summary>
    public static string Active
    {
        get { return ResourceManager.GetString("Active", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Show.
    /// </summary>
    public static string Show
    {
        get { return ResourceManager.GetString("Show", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Hide.
    /// </summary>
    public static string Hide
    {
        get { return ResourceManager.GetString("Hide", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Login to Claude.
    /// </summary>
    public static string LoginTitle
    {
        get { return ResourceManager.GetString("LoginTitle", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Initializing browser....
    /// </summary>
    public static string LoginInitializing
    {
        get { return ResourceManager.GetString("LoginInitializing", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Loading login page....
    /// </summary>
    public static string LoginLoading
    {
        get { return ResourceManager.GetString("LoginLoading", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Waiting for login....
    /// </summary>
    public static string LoginWaiting
    {
        get { return ResourceManager.GetString("LoginWaiting", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Login detected!.
    /// </summary>
    public static string LoginDetected
    {
        get { return ResourceManager.GetString("LoginDetected", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Fetching organizations....
    /// </summary>
    public static string LoginFetchingOrgs
    {
        get { return ResourceManager.GetString("LoginFetchingOrgs", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Login Error.
    /// </summary>
    public static string LoginError
    {
        get { return ResourceManager.GetString("LoginError", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to No organizations found for this account..
    /// </summary>
    public static string LoginNoOrgs
    {
        get { return ResourceManager.GetString("LoginNoOrgs", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Failed to fetch organizations: {0}.
    /// </summary>
    public static string LoginFetchError
    {
        get { return ResourceManager.GetString("LoginFetchError", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Select Organization.
    /// </summary>
    public static string SelectOrganization
    {
        get { return ResourceManager.GetString("SelectOrganization", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Select the organizations you want to add:.
    /// </summary>
    public static string SelectOrgsDescription
    {
        get { return ResourceManager.GetString("SelectOrgsDescription", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Select All.
    /// </summary>
    public static string SelectAll
    {
        get { return ResourceManager.GetString("SelectAll", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cancel.
    /// </summary>
    public static string Cancel
    {
        get { return ResourceManager.GetString("Cancel", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to OK.
    /// </summary>
    public static string OK
    {
        get { return ResourceManager.GetString("OK", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to 1 min.
    /// </summary>
    public static string Interval1min
    {
        get { return ResourceManager.GetString("Interval1min", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to 2 min.
    /// </summary>
    public static string Interval2min
    {
        get { return ResourceManager.GetString("Interval2min", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to 3 min.
    /// </summary>
    public static string Interval3min
    {
        get { return ResourceManager.GetString("Interval3min", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to 5 min.
    /// </summary>
    public static string Interval5min
    {
        get { return ResourceManager.GetString("Interval5min", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to 10 min.
    /// </summary>
    public static string Interval10min
    {
        get { return ResourceManager.GetString("Interval10min", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Usage is at {0:F0}%.
    /// </summary>
    public static string NotifHighUsage
    {
        get { return ResourceManager.GetString("NotifHighUsage", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Usage limit has been reset.
    /// </summary>
    public static string NotifLimitReset
    {
        get { return ResourceManager.GetString("NotifLimitReset", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Failed to refresh usage data.
    /// </summary>
    public static string NotifRefreshError
    {
        get { return ResourceManager.GetString("NotifRefreshError", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to About.
    /// </summary>
    public static string AboutSection
    {
        get { return ResourceManager.GetString("AboutSection", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to A Windows system tray application for monitoring Claude AI usage quotas..
    /// </summary>
    public static string AboutDescription
    {
        get { return ResourceManager.GetString("AboutDescription", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Version.
    /// </summary>
    public static string Version
    {
        get { return ResourceManager.GetString("Version", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to GitHub Repository.
    /// </summary>
    public static string GitHubRepo
    {
        get { return ResourceManager.GetString("GitHubRepo", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Report an Issue.
    /// </summary>
    public static string ReportIssue
    {
        get { return ResourceManager.GetString("ReportIssue", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Credits.
    /// </summary>
    public static string Credits
    {
        get { return ResourceManager.GetString("Credits", resourceCulture)!; }
    }

    /// <summary>
    ///   Looks up a localized string similar to Usage4Claude is already running..
    /// </summary>
    public static string AlreadyRunning
    {
        get { return ResourceManager.GetString("AlreadyRunning", resourceCulture)!; }
    }
}
